"use client";

import { useEffect, useState } from "react";
import { MapPin, Clock, CheckCircle2, AlertTriangle, RefreshCw, Plus, Trash2, Search, Bell, ArrowLeft, Edit, X } from "lucide-react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { deliveriesApi } from "@/lib/services";
import dynamic from "next/dynamic";

const LiveMap = dynamic(() => import("@/components/ui/LiveMap"), { ssr: false });

const STATUS_STYLES: Record<string, string> = {
  "In Transit": "text-tertiary bg-tertiary/10",
  Delayed: "text-error bg-error/10",
  Pending: "text-secondary bg-secondary/10",
  Delivered: "text-green-400 bg-green-400/10",
};

const STATUS_BAR: Record<string, string> = {
  "In Transit": "bg-tertiary",
  Delayed: "bg-error",
  Pending: "bg-secondary",
  Delivered: "bg-green-400",
};

export default function DeliveriesPage() {
  const [deliveries, setDeliveries] = useState<any[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ delivery_code: "", driver: "", location: "", progress: "0", eta: "" });
  const [saving, setSaving] = useState(false);
  const [editTarget, setEditTarget] = useState<any | null>(null);
  const [editForm, setEditForm] = useState({ location: "", progress: "", eta: "", status: "" });
  const [editSaving, setEditSaving] = useState(false);

  function openEdit(d: any) {
    setEditTarget(d);
    setEditForm({ location: d.location ?? "", progress: String(d.progress ?? 0), eta: d.eta ?? "", status: d.status ?? "Pending" });
  }

  async function saveEdit(e: React.FormEvent) {
    e.preventDefault();
    if (!editTarget) return;
    setEditSaving(true);
    try { await deliveriesApi.update(editTarget.id, { ...editForm, progress: parseInt(editForm.progress) }); setEditTarget(null); load(); } catch { /* ignore */ }
    setEditSaving(false);
  }

  async function load() {
    setLoading(true);
    try {
      const data = await deliveriesApi.list();
      setDeliveries(data ?? []);
    } catch {
      setDeliveries([]);
    }
    setLoading(false);
  }

  useEffect(() => { load(); }, []);

  const [selected, setSelected] = useState<any>(null);
  const [notifySent, setNotifySent] = useState<string | null>(null);

  async function handleStatusUpdate(d: any, newStatus: string) {
    try {
      await deliveriesApi.update(d.id, { status: newStatus });
    } catch { /* ignore */ }
    setNotifySent(d.id);
    load();
  }
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      // delivery_code is auto-generated by the backend — never sent.
      // driver is a free-text UI field with no backend column — omitted.
      await deliveriesApi.create({
        location: form.location,
        progress: parseInt(form.progress),
        eta: form.eta,
        status: "Pending",
      });
      setForm({ delivery_code: "", driver: "", location: "", progress: "0", eta: "" });
      setShowForm(false);
    } catch { /* ignore */ }
    setSaving(false);
    load();
  }

  async function handleDelete(id: string) {
    try { await deliveriesApi.remove(id); } catch { /* ignore */ }
    load();
  }

  const filtered = deliveries.filter((d) =>
    d.delivery_code?.toLowerCase().includes(search.toLowerCase()) ||
    d.driver?.toLowerCase().includes(search.toLowerCase()) ||
    d.status?.toLowerCase().includes(search.toLowerCase())
  );

  const inputCls = "mt-1 w-full px-3 py-2 rounded-lg bg-surface-container border border-white/10 text-sm text-on-surface placeholder:text-on-surface-variant/50 focus:outline-none focus:border-tertiary/50";

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <Link href="/logistics" className="inline-flex items-center gap-2 mb-4 px-5 py-2.5 rounded-xl bg-[#00C2FF] hover:bg-[#00a8e0] transition-colors w-fit shadow-[0_4px_16px_rgba(0,194,255,0.35)]">
            <ArrowLeft className="h-4 w-4 text-[#0B1F3A]" />
            <span className="text-sm font-bold text-[#0B1F3A]">← Back to Dashboard</span>
          </Link>
          <p className="text-xs uppercase tracking-widest text-tertiary">Logistics</p>
          <h1 className="text-3xl font-bold text-on-surface mt-1">Delivery Tracking</h1>
          <p className="text-sm text-on-surface-variant mt-1">Monitor delivery progress in real time from Supabase.</p>
        </div>
        <div className="flex gap-2 shrink-0">
          <button onClick={load} className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-white/5 text-on-surface-variant text-xs font-semibold hover:bg-white/10 transition-colors"><RefreshCw className="h-4 w-4" /></button>
          <button onClick={() => setShowForm(!showForm)} className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-tertiary/20 text-tertiary text-xs font-semibold hover:bg-tertiary/30 transition-colors"><Plus className="h-4 w-4" /> Add Delivery</button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        {[
          { label: "Total", value: deliveries.length, color: "text-tertiary bg-tertiary/10", Icon: MapPin },
          { label: "In Transit", value: deliveries.filter(d => d.status === "In Transit").length, color: "text-secondary bg-secondary/10", Icon: Clock },
          { label: "Delayed", value: deliveries.filter(d => d.status === "Delayed").length, color: "text-error bg-error/10", Icon: AlertTriangle },
          { label: "Delivered", value: deliveries.filter(d => d.status === "Delivered").length, color: "text-green-400 bg-green-400/10", Icon: CheckCircle2 },
        ].map(({ label, value, color, Icon }) => (
          <Card key={label} className="p-5 flex items-center gap-4">
            <span className={`flex h-10 w-10 items-center justify-center rounded-lg ${color}`}><Icon className="h-5 w-5" /></span>
            <div>
              <p className="font-mono text-2xl font-bold text-on-surface">{loading ? "—" : value}</p>
              <p className="text-[11px] uppercase tracking-widest text-on-surface-variant">{label}</p>
            </div>
          </Card>
        ))}
      </div>

      {/* Live Map for selected delivery */}
      {selected && (
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold uppercase tracking-widest text-on-surface-variant">Live GPS — {selected.delivery_code}</h2>
            <button onClick={() => setSelected(null)} className="text-xs text-on-surface-variant hover:text-on-surface">✕ Close</button>
          </div>
          <LiveMap lat={selected.lat ?? 1.3521} lng={selected.lng ?? 103.8198} label={selected.location ?? selected.delivery_code} height={280} />
          <div className="flex flex-wrap gap-2 pt-1">
            {["Pending","In Transit","Delayed","Delivered"].map((s) => (
              <button key={s} onClick={() => handleStatusUpdate(selected, s)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${
                  selected.status === s ? "bg-tertiary/20 text-tertiary" : "bg-white/5 text-on-surface-variant hover:bg-white/10"
                }`}>{s}</button>
            ))}
            {notifySent === selected.id && (
              <span className="flex items-center gap-1.5 text-xs text-green-400"><Bell className="h-3.5 w-3.5" /> SMS & Email sent</span>
            )}
          </div>
        </div>
      )}

      {showForm && (
        <>
    <h2 className="text-sm font-semibold uppercase tracking-wide...">Delivery</h2>
    <form noValidate onSubmit={handleSubmit} className="space-y-4">
     

  
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Delivery Code</label><input required value={form.delivery_code} onChange={(e) => setForm({ ...form, delivery_code: e.target.value })} placeholder="e.g. DEL-9000" className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Driver</label><input required value={form.driver} onChange={(e) => setForm({ ...form, driver: e.target.value })} placeholder="e.g. Marcus Johnson" className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Current Location</label><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="e.g. North Sea" className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Progress (%)</label><input type="number" min="0" max="100" value={form.progress} onChange={(e) => setForm({ ...form, progress: e.target.value })} className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">ETA</label><input value={form.eta} onChange={(e) => setForm({ ...form, eta: e.target.value })} placeholder="e.g. May 24, 14:00" className={inputCls} /></div>
            </div>
            <div className="flex gap-3">
              <button type="submit" disabled={saving} className="px-4 py-2 rounded-lg bg-tertiary/20 text-tertiary text-sm font-semibold hover:bg-tertiary/30 transition-colors disabled:opacity-50">{saving ? "Saving…" : "Save"}</button>
              <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 rounded-lg bg-white/5 text-on-surface-variant text-sm font-semibold hover:bg-white/10 transition-colors">Cancel</button>
            </div>
          </form>
        {/* </Card> */}
      </>
      )}

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-on-surface-variant" />
        <input type="text" placeholder="Search deliveries…" value={search} onChange={(e) => setSearch(e.target.value)} className="w-full pl-9 pr-4 py-2.5 rounded-lg bg-surface-container border border-white/10 text-sm text-on-surface placeholder:text-on-surface-variant focus:outline-none focus:border-tertiary/50" />
      </div>

      {loading ? <Card className="p-6 text-sm text-on-surface-variant">Loading from Supabase…</Card> : (
        <div className="space-y-4">
          {filtered.map((d) => (
            <Card key={d.id} className={`p-5 group cursor-pointer transition-all ${selected?.id === d.id ? "border-tertiary/40" : ""}`} onClick={() => setSelected(d)}>
              <div className="flex items-start justify-between gap-3 mb-4">
                <div>
                  <p className="font-mono text-xs text-tertiary">{d.delivery_code}</p>
                  <p className="text-sm font-semibold text-on-surface mt-0.5">Driver: {d.driver}</p>
                  {d.location && <p className="text-xs text-on-surface-variant flex items-center gap-1 mt-0.5"><MapPin className="h-3 w-3" />{d.location}</p>}
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className={`rounded-full px-2.5 py-0.5 text-[11px] font-semibold ${STATUS_STYLES[d.status] ?? ""}`}>{d.status}</span>
                  <button onClick={(e) => { e.stopPropagation(); openEdit(d); }} className="p-1.5 rounded-lg hover:bg-tertiary/10 text-tertiary opacity-0 group-hover:opacity-100 transition-all" title="Edit"><Edit className="h-4 w-4" /></button>
                  <button onClick={(e) => { e.stopPropagation(); handleDelete(d.id); }} className="opacity-0 group-hover:opacity-100 p-1.5 rounded-lg hover:bg-error/10 text-error transition-all"><Trash2 className="h-4 w-4" /></button>
                </div>
              </div>
              <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden mb-2">
                <div className={`h-full rounded-full transition-all ${STATUS_BAR[d.status] ?? "bg-white/20"}`} style={{ width: `${d.progress ?? 0}%` }} />
              </div>
              <div className="flex justify-between text-xs text-on-surface-variant">
                <span>{d.progress ?? 0}% complete</span>
                {d.eta && <span className="flex items-center gap-1"><Clock className="h-3 w-3" />ETA: {d.eta}</span>}
              </div>
            </Card>
          ))}
          {filtered.length === 0 && <Card className="p-8 text-center text-on-surface-variant text-sm">No deliveries found.</Card>}
        </div>
      )}
      {editTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-2xl border border-white/10 bg-surface-container shadow-2xl">
            <div className="flex items-center justify-between px-6 py-4 border-b border-white/8">
              <h2 className="text-base font-bold text-on-surface">Edit Delivery</h2>
              <button onClick={() => setEditTarget(null)} className="p-1.5 rounded-lg hover:bg-white/10 text-on-surface-variant"><X className="h-4 w-4" /></button>
            </div>
            <form noValidate onSubmit={saveEdit} className="p-6 space-y-4">
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Location</label><input value={editForm.location} onChange={e => setEditForm(p => ({...p, location: e.target.value}))} className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Progress (%)</label><input type="number" min="0" max="100" value={editForm.progress} onChange={e => setEditForm(p => ({...p, progress: e.target.value}))} className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">ETA</label><input value={editForm.eta} onChange={e => setEditForm(p => ({...p, eta: e.target.value}))} className={inputCls} /></div>
              <div><label className="text-xs uppercase tracking-widest text-on-surface-variant">Status</label>
                <select value={editForm.status} onChange={e => setEditForm(p => ({...p, status: e.target.value}))} className={inputCls}>
                  <option>Pending</option><option>In Transit</option><option>Delayed</option><option>Delivered</option>
                </select>
              </div>
              <div className="flex gap-3 pt-2">
                <button type="submit" disabled={editSaving} className="flex-1 py-2.5 rounded-xl bg-[#1E88E5] text-white font-bold text-sm hover:bg-[#1565C0] disabled:opacity-50">{editSaving ? "Saving…" : "Save Changes"}</button>
                <button type="button" onClick={() => setEditTarget(null)} className="px-5 py-2.5 rounded-xl border border-white/10 bg-white/5 text-sm font-semibold text-on-surface-variant hover:bg-white/10">Cancel</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
